// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkobyxmrzqxhtuqxcudy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imprb2J5eG1yenF4aHR1cXhjdWR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTUwODEsImV4cCI6MjA2NTQ3MTA4MX0.qw0NGAoLmg6kpvAyQKLvySwM6cBPfWKeroN1sP81m6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);